### ISSUE TITLE
Class Attributes

### ISSUE THREAD

**Issue by jwaldrop107** [CMakePP/CMakePPCore#19]
@blakemulnix, there appears to be an issue when getting and setting class attributes as a list after the latest PR.

**Comment by ryanmrichard** [comment]
To add some more context, try checking out [Utilties](https://github.com/NWChemEx-Project/Utilities) and building it. What you'll see is that it only builds the first source file for the library and the executable for testing. As far as I can tell, the problem occurs somewhere between when the list of sources is added to the target instance and when they are retrieved (I suspect the problem occurs for the header files as well, but that's less pronounced in the build process).
